### ISSUE TITLE
Unable to apply patch to DSCSCE - Exception while compiling

### ISSUE THREAD

**Issue by h0rus96** [Pherakki/DSCS-SkipDialogueMod#3]
If 'Complete Edition' is incompatible then I'm sorry for bothering you.

The Modmanager crashes while applying the mod during compiling.

Used:
v0.2 release of DSCS-SkipDialogueMod
v0.1-alpha.5 of SimpleDSCSModManager

log.txt is left empty

After checking the contents of 'battle_0011.txt' the file, along with 'battle_0000.txt', 'battle_0001.txt' and 'battle_0511.txt' have the line 'Error: Unknown exception' at the top.

Traceback generated by PowerShell:

PS D:\Games\Digimon Story Cyber Sleuth Mod Manager 1> .\SimpleDSCSModManagerDEBUG.exe
Traceback (most recent call last):
  File "CodeHandlers\ScriptWorker.py", line 76, in raise_exception
CodeHandlers.ScriptWorker.ScriptHandlerError: (Exception(b'D:\\Games\\Digimon Story Cyber Sleuth Mod Manager 1\\output\\patch\\DSDBP\\script64\\battle_0011.txt line = (1) column = (6) : error end of statement expected (; or lf)\r\nError [end of statement expected (; or lf)]\r\n'), 'battle_0011.txt')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CodeHandlers\ScriptWorker.py", line 81, in raise_exception
  File "CodeHandlers\ScriptWorker.py", line 110, in run
  File "CodeHandlers\ScriptHandler.py", line 23, in compile_script
Exception: b'D:\\Games\\Digimon Story Cyber Sleuth Mod Manager 1\\output\\patch\\DSDBP\\script64\\battle_0011.txt line = (1) column = (6) : error end of statement expected (; or lf)\r\nError [end of statement expected (; or lf)]\r\n'

[battle_0011.txt](https://github.com/Pherakki/DSCS-SkipDialogueMod/files/7274681/battle_0011.txt)
[battle_0511.txt](https://github.com/Pherakki/DSCS-SkipDialogueMod/files/7274682/battle_0511.txt)
[battle_0000.txt](https://github.com/Pherakki/DSCS-SkipDialogueMod/files/7274683/battle_0000.txt)
[battle_0001.txt](https://github.com/Pherakki/DSCS-SkipDialogueMod/files/7274684/battle_0001.txt)

**Comment by Pherakki** [comment]
Thank you for the detailed bug report. This is actually caused by a known error with the NutCracker tool used by SimpleDSCSModManager, with the cause currently unknown. Can you tell me the size of the file located at tools/nutcracker/NutCracker.exe in your mod manager install, so I can verify that you have the version for which this bug should have been fixed?

**Comment by Pherakki** [comment]
Also, you seem to have attached the script files from the mod rather than those causing the error (which is understandable since it is not obvious that the mod is not the source of the error); the ones that cause the problems are located at
`\output\patch\DSDBP\script64\`. If this is similar to what has been reported before, there will be some missing brackets in the scripts that cause the parse failure given in your report. Taking a look at those scripts to make sure the error doesn't manifest in a different way could still be useful though.

Edit: I'm stupid, I didn't notice the line "Error: Unknown Exception" at the top of the files (or your comment stating this was there), which is why they looked like the regular mod files to me.

**Comment by h0rus96** [comment]
Hi, my NutCracker.exe is 193KB. And I can confirm that the 4 .txt files come from the the output folder.

Additionally I've been able to force the install by removing the copy commands for the 4 files from the INSTALL.json file in the mod, and installing the mod normally.

Maybe it's a difference with the 'Complete Edition', but when I extract the scripts and decompile them the 4 problem .txts are not being generated.

**Comment by Pherakki** [comment]
Very interesting. Thanks for the follow-up. 
This mod has been developed for the "Complete Edition" on PC, so it should be working for it.
Removing those copy commands and re-registering the mod will mean that the mod won't affect those four files; i.e. those four battles won't have any dialogue skipping, which is why those four scripts are no longer generated in the patch. Admittedly, I'm not sure whether those battles actually contain any dialogue.

The issue is likely that the decompiled scripts in `resources/base_scripts/script64/` have decompiled incorrectly. I can confirm this if you upload the four scripts from that location, but I'm still not 100% sure what the root cause of this decompilation error is, since it seems somewhat random currently who experiences this error and who doesn't, and which files don't decompile correctly...

If those files only contain the words "Error: Unknown Exception", that would be a very interesting new development we can investigate if you're willing to help do some debugging.

**Comment by h0rus96** [comment]
Don't have much free time these days but I'll help where I can.

Regarding the scripts you requested, they indeed contain only "Error: Unknown Exception".

These are the files:

[battle_0511.txt](https://github.com/Pherakki/DSCS-SkipDialogueMod/files/7289862/battle_0511.txt)
[battle_0000.txt](https://github.com/Pherakki/DSCS-SkipDialogueMod/files/7289863/battle_0000.txt)
[battle_0001.txt](https://github.com/Pherakki/DSCS-SkipDialogueMod/files/7289864/battle_0001.txt)
[battle_0011.txt](https://github.com/Pherakki/DSCS-SkipDialogueMod/files/7289865/battle_0011.txt)


Anyway, unpacking the game using the Manager "Extract" -> "Extract DSDB" generates the files correctly and, if I replace the ones in  'resources/base_scripts/script64/' with the files I extracted+decompiled, the Mod install goes through with no issues.

I did try moving my install of 'Complete Edition' to a different drive (not C:), and moved the mod manager to the root of the drive (unlikely to be the 256-character path length, bud did it anyway), and I have run 'fresh installs' of SimpleDSCSModManager each time  (both with and without administrator privileges).

All 4 (5?) times I have tried, the result is the same, these 4 specific files are not decompiled correctly.



EDIT:

Running the ModManager from the root of a drive (F:\SimpleDSCSModManagerDEBUG.exe) as administrator with AV disabled works.

I don't understand why it would have issues with these 4 specific files, but it seems to be something with Windows' permissions or something truly random.

Anyway if you want me to check anything just let me know.

**Comment by Pherakki** [comment]
Thanks for checking with the AV disabling and admin mode. That is a really useful result.

My guess at what is happening is that the multithreading triggers Windows or your AV in some manner - I don't think the manual extraction processes are multithreaded. This is also why the first 4 files are corrupt - I'm guessing your CPU has 4 hardware threads / non-hyperthreaded cores?

That's my guess, anyway. To help diagnose the root cause here, it would be exceptionally useful if you could:
1) Check whether just turning off the AV works (and if turning off the AV works, check if adding the mod manager as an exception helps?). From a non-protected location like the root of your F: drive is ok for this test; if you want to also try in a protected location like `Documents/` or `Desktop/` that could be interesting too (but not necessary since the mod manager README says to put it in a non-protected location)
2) If (1) is solely due to the AV, please let me know what AV you're using so I can check if this is consistent with other people who experience this problem.

Thanks for the info!

Edit: Nope, the manual extraction is still multithreaded, so the mystery deepens. If it is your AV, I think I know what is causing it, and I don't think it's fixable without totally rewriting the mod manager in another language with a better build process (which I kind've want to do anyway).

**Comment by h0rus96** [comment]
I keep my Game Library, Launchers, ModManagers etc on a separate drive that is excluded from the AV (Avast), so I didn't consider that the AV could be a issue, but my experience with Windows tells me that nothing is ever certain.

I have a 6th Gen i7 so you are right that it is a 4+4.

This is the OS version:
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1266
Experience	Windows Feature Experience Pack 120.2212.3920.0


It's an interesting issue, with the AV disabled, the ModManager will decompile the file correctly regardless of the location (root of F:\, C:\ModManager\, Documents folder, Desktop, and inside my Games Drive), if I turn on the AV none of them work (always the 4 files). Admin privileges does not affect the end result.

I was curious about your hyperthreading comment, I disabled Hyperthreading inside the UEFI, and, even with the AV left working, the Modmanager had no problems decompiling the files and installing the mod (tested inside a protected folder and from inside the Games Drive).

It's a truly weird issue, I'm able to use the ModManager to apply other mods with no issues, but something about decompiling the scripts makes Windows/Avast freakout.

**Comment by Pherakki** [comment]
Thanks for doing those investigations, that's very interesting. I haven't been able to draw a direct link between hyperthreads and this error, but the AV seems to be a consistent cause of trouble. I think this may be due to my use of PyInstaller as a deployment tool, which is known to trip out AVs. This issue has been plaguing the manager for a while, so I'm very grateful that you did those tests and confirmed the AV as a source of interference.

Since it seems like you've got a way to get the mod to install and found a cause for the bug, I propose that we close this issue and I will add a warning to the mod manager stating that turning off the AV may resolve issues with script mod installation.
